[package]
name = "cargo-bitbake-test"
version = "0.1.0"
edition = "2018"
repository = "https://github.com/orrinjelo/cargo-bitbake-test.git"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
